"""Create notes table

Revision ID: c7f54eb3c0e3
Revises:
Create Date: 2025-11-20 20:09:11.592289

"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "c7f54eb3c0e3"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    """Upgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "notes",
        sa.Column(
            "id",
            sa.Uuid(),
            server_default=sa.text("gen_random_uuid()"),
            nullable=False,
            comment="Unique identifier",
        ),
        sa.Column(
            "session_id",
            sa.Uuid(),
            nullable=True,
            comment="Optional session ID for AI-generated notes",
        ),
        sa.Column("title", sa.String(), nullable=False, comment="Title of the Note"),
        sa.Column("content", sa.Text(), nullable=False, comment="Content of the Note"),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
            comment="Timestamp when created",
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
            comment="Timestamp when last updated",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_notes_created_at",
        "notes",
        ["created_at"],
        unique=False,
        postgresql_ops={"created_at": "DESC"},
    )
    op.create_index(op.f("ix_notes_title"), "notes", ["title"], unique=False)
    op.create_index(op.f("ix_notes_session_id"), "notes", ["session_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_notes_session_id"), table_name="notes")
    op.drop_index(op.f("ix_notes_title"), table_name="notes")
    op.drop_index("idx_notes_created_at", table_name="notes", postgresql_ops={"created_at": "DESC"})
    op.drop_table("notes")
    # ### end Alembic commands ###
